---
## this is the settings file
## widths are in inches
settings:
  ## what files to search for
  ## see globbing rules here : https://docs.python.org/3/library/glob.html
  filetypes:
    glob: "*.srt"

  ## single file mode, false for multi-file
  single_file: true

  ## table settings
  table:
    headers: ["start", "end", "delta", "content"]
  ## margins
  layout:
    margin_left: 0.25
    margin_right: 0.25
    ## column widths
    table_cols: [0.75,0.75,0.75,5.65]
    ## title formatting
    title:
      size: 16
      color: "AE8A40"
    ## document fonts
    fonts:
      Normal: "Arial"
      Title: "Arial"

  ## document meta data
  meta:
    author: "someone@example.com"
    category: "video"
    comments: "This is just an exmaple xyzzy"
    content_status: "draft"
    keywords: "example,test,demo,srt"
    language: "en"
    subject: "testing"
    version: "1.0.0"
  ## footer settings
  footer:
    show: true
    watermark: "flour006.png"
    width_in: 0.50